sonar.projectKey=fastapi-react-cicd-poc
sonar.projectName=FastAPI React CI/CD PoC
sonar.projectVersion=1.0

sonar.sources=backend/app
sonar.exclusions=**/node_modules/**,**/venv/**,**/test-venv/**,frontend/**

sonar.python.version=3.10
sonar.sourceEncoding=UTF-8

